// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl6VkUZdC1fnUq_Kx57qE6XuzaZP9MrbY',
    appId: '1:1041247828311:web:6c4d65efe775b180256612',
    messagingSenderId: '1041247828311',
    projectId: 'messageapp-597f7',
    authDomain: 'messageapp-597f7.firebaseapp.com',
    storageBucket: 'messageapp-597f7.appspot.com',
    measurementId: 'G-3WJS7HP7DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDiHaUOs33gvceeZFhDDPO9qdpGA4dbs0',
    appId: '1:1041247828311:android:c286d7701eceed3d256612',
    messagingSenderId: '1041247828311',
    projectId: 'messageapp-597f7',
    storageBucket: 'messageapp-597f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhVGDF3S-GOtXkEdjmQZWKs8QsY5QDbig',
    appId: '1:1041247828311:ios:e0e1e801992db78e256612',
    messagingSenderId: '1041247828311',
    projectId: 'messageapp-597f7',
    storageBucket: 'messageapp-597f7.appspot.com',
    iosClientId: '1041247828311-0ur4m927en7vm11pmdhr187t262hdqac.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhVGDF3S-GOtXkEdjmQZWKs8QsY5QDbig',
    appId: '1:1041247828311:ios:e0e1e801992db78e256612',
    messagingSenderId: '1041247828311',
    projectId: 'messageapp-597f7',
    storageBucket: 'messageapp-597f7.appspot.com',
    iosClientId: '1041247828311-0ur4m927en7vm11pmdhr187t262hdqac.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp',
  );
}
